I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 25, in script call
    call act1_scene01
  File "game/act1.rpy", line 176, in script
    $ front_door_gone_throught = true
  File "game/act1.rpy", line 176, in <module>
    $ front_door_gone_throught = true
NameError: name 'true' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 25, in script call
    call act1_scene01
  File "game/act1.rpy", line 176, in script
    $ front_door_gone_throught = true
  File "F:\PROGRAM FILES 2\Ren Py\renpy-8.2.1-sdk\renpy\ast.py", line 821, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "F:\PROGRAM FILES 2\Ren Py\renpy-8.2.1-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/act1.rpy", line 176, in <module>
    $ front_door_gone_throught = true
NameError: name 'true' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.2.24090902
Halloween Party 1.0
Wed Sep 25 14:28:27 2024
